### ISSUE TITLE
Add dangerous commands detection feature for subcommand `command` and `script`

### ISSUE THREAD

**Issue by windvalley** [windvalley/gossh#34]
For security reasons, it is necessary to provide a feature for detecting dangerous commands, and user can customize the command blacklist. If there is no customization, the default blacklist provided by the tool will be used.

The command line:

```sh
$ gossh command -h    OR    $ gossh script -h
...
Flags:
...
  -n, --no-safe-check    ignore dangerous commands (from '-B,--run.command-blacklist') check
...
Global Flags:
...
  -B, --run.command-blacklist strings   commands that are prohibited from execution on target hosts
                                        (default: rm,reboot,halt,shutdown,init,mkfs,mkfs.*,umount,dd)
...
```

Or  customize command blacklist in config file:

```yaml
run:
  # Linux Command Blacklist for gossh subcommands 'command' and 'script'.
  # Commands listed in this blacklist will be prohibited from executing on remote hosts for security reasons.
  # You can add flag '-n, --no-safe-check' to disable this feature.
  # Default: ["rm", "reboot", "halt", "shutdown", "init", "mkfs", "mkfs.*", "umount", "dd"]
  command-blacklist: []
```
